name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Angular CLI
      run: npm install -g @angular/cli angular-cli-ghpages

    - name: Install dependencies
      run: npm install
      
    - name: Switch to demo_app directory
      run: cd demo_app

    - name: Build and deploy
      run: |
        ng build -- --base-href=/demo_app/
        ngh --dir=dist/demo_app --no-silent